//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PennyTechManagementSystem {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NameHandling {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NameHandling() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PennyTechManagementSystem.NameHandling", typeof(NameHandling).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builty Number.
        /// </summary>
        public static string BuiltyNumber {
            get {
                return ResourceManager.GetString("BuiltyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chasis Number.
        /// </summary>
        public static string ChasisNumber {
            get {
                return ResourceManager.GetString("ChasisNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Pity Cash.
        /// </summary>
        public static string DailyPityCash {
            get {
                return ResourceManager.GetString("DailyPityCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation Name.
        /// </summary>
        public static string DesignationName {
            get {
                return ResourceManager.GetString("DesignationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Location.
        /// </summary>
        public static string DestinationLocation {
            get {
                return ResourceManager.GetString("DestinationLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver CNIC.
        /// </summary>
        public static string DriverCNIC {
            get {
                return ResourceManager.GetString("DriverCNIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Mobile.
        /// </summary>
        public static string DriverMobile {
            get {
                return ResourceManager.GetString("DriverMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Name.
        /// </summary>
        public static string DriverName {
            get {
                return ResourceManager.GetString("DriverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving Licence Number.
        /// </summary>
        public static string DrivingLicenceNumber {
            get {
                return ResourceManager.GetString("DrivingLicenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Horse Power.
        /// </summary>
        public static string EngineHorsePower {
            get {
                return ResourceManager.GetString("EngineHorsePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Number.
        /// </summary>
        public static string EngineNumber {
            get {
                return ResourceManager.GetString("EngineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error occured while executing your request.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reques can not be completed.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Time.
        /// </summary>
        public static string EstimatedTime {
            get {
                return ResourceManager.GetString("EstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expence Category Name.
        /// </summary>
        public static string ExpenceCategoryName {
            get {
                return ResourceManager.GetString("ExpenceCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expence Mode.
        /// </summary>
        public static string ExpenceMode {
            get {
                return ResourceManager.GetString("ExpenceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expence Name.
        /// </summary>
        public static string ExpenceName {
            get {
                return ResourceManager.GetString("ExpenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Amount.
        /// </summary>
        public static string FuelAmount {
            get {
                return ResourceManager.GetString("FuelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Litre.
        /// </summary>
        public static string FuelLitre {
            get {
                return ResourceManager.GetString("FuelLitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Rate.
        /// </summary>
        public static string FuelRate {
            get {
                return ResourceManager.GetString("FuelRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Weight.
        /// </summary>
        public static string LoadedWeight {
            get {
                return ResourceManager.GetString("LoadedWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture Date.
        /// </summary>
        public static string ManufactureDate {
            get {
                return ResourceManager.GetString("ManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufactured From.
        /// </summary>
        public static string ManufacturedFrom {
            get {
                return ResourceManager.GetString("ManufacturedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year.
        /// </summary>
        public static string ModelYear {
            get {
                return ResourceManager.GetString("ModelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Wheels.
        /// </summary>
        public static string NumberOfWheels {
            get {
                return ResourceManager.GetString("NumberOfWheels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Company Name.
        /// </summary>
        public static string OrderCompanyName {
            get {
                return ResourceManager.GetString("OrderCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Person Contact.
        /// </summary>
        public static string OrderPersonContact {
            get {
                return ResourceManager.GetString("OrderPersonContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Person Name.
        /// </summary>
        public static string OrderPersonName {
            get {
                return ResourceManager.GetString("OrderPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date.
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase From.
        /// </summary>
        public static string PurchaseFrom {
            get {
                return ResourceManager.GetString("PurchaseFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Date.
        /// </summary>
        public static string ReferenceDate {
            get {
                return ResourceManager.GetString("ReferenceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent Amount.
        /// </summary>
        public static string RentAmount {
            get {
                return ResourceManager.GetString("RentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RentIn Date.
        /// </summary>
        public static string RentInDate {
            get {
                return ResourceManager.GetString("RentInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned.
        /// </summary>
        public static string Returned {
            get {
                return ResourceManager.GetString("Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned Date.
        /// </summary>
        public static string ReturnedDate {
            get {
                return ResourceManager.GetString("ReturnedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipment Name.
        /// </summary>
        public static string ShipmentName {
            get {
                return ResourceManager.GetString("ShipmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Location.
        /// </summary>
        public static string SourceLocation {
            get {
                return ResourceManager.GetString("SourceLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Meter Reading.
        /// </summary>
        public static string StartingMeterReading {
            get {
                return ResourceManager.GetString("StartingMeterReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your request for deleting is completed successfully.
        /// </summary>
        public static string SuccessMessageDelete {
            get {
                return ResourceManager.GetString("SuccessMessageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved Successfully.
        /// </summary>
        public static string SuccessSave {
            get {
                return ResourceManager.GetString("SuccessSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Business Type Name.
        /// </summary>
        public static string VehicleBusinessTypeName {
            get {
                return ResourceManager.GetString("VehicleBusinessTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Busuness Type.
        /// </summary>
        public static string VehicleBusunessType {
            get {
                return ResourceManager.GetString("VehicleBusunessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Company Name.
        /// </summary>
        public static string VehicleCompanyName {
            get {
                return ResourceManager.GetString("VehicleCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Lenght.
        /// </summary>
        public static string VehicleLenght {
            get {
                return ResourceManager.GetString("VehicleLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Model Name.
        /// </summary>
        public static string VehicleModelName {
            get {
                return ResourceManager.GetString("VehicleModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Number.
        /// </summary>
        public static string VehicleNumber {
            get {
                return ResourceManager.GetString("VehicleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Owner Name.
        /// </summary>
        public static string VehicleOwnerName {
            get {
                return ResourceManager.GetString("VehicleOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type Name.
        /// </summary>
        public static string VehicleTypeName {
            get {
                return ResourceManager.GetString("VehicleTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name.
        /// </summary>
        public static string VendorName {
            get {
                return ResourceManager.GetString("VendorName", resourceCulture);
            }
        }
    }
}
